apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # admin (base64)
  username: YWRtaW4=
  # password123 (base64)
  password: cGFzc3dvcmQxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  # mi-secreto-super-seguro-cambiar-en-produccion (base64)
  secret: bWktc2VjcmV0by1zdXBlci1zZWd1cm8tY2FtYmlhci1lbi1wcm9kdWNjaW9u
